# config.py
DATASETS = {
    "heart": {
        "name": "Heart Disease",
        "path": "backend/data/heart.csv",
        "target_column": "target",
        "class_labels": {0: "No Heart Disease", 1: "Heart Disease"},
        "feature_types": {
            "age": "numeric",
            "sex": "numeric",
            "cp": "numeric",
            "trestbps": "numeric",
            "chol": "numeric",
            "fbs": "numeric",
            "restecg": "numeric",
            "thalach": "numeric",
            "exang": "numeric",
            "oldpeak": "numeric",
            "slope": "numeric",
            "ca": "numeric",
            "thal": "numeric"
        }
    },
    "diabetes": {
        "name": "Diabetes Prediction",
        "path": "backend/data/diabetes.csv",
        "target_column": "Outcome",
        "class_labels": {0: "No Diabetes", 1: "Diabetes"},
        "feature_types": {
            "Pregnancies": "numeric",
            "Glucose": "numeric",
            "BloodPressure": "numeric",
            "SkinThickness": "numeric",
            "Insulin": "numeric",
            "BMI": "numeric",
            "DiabetesPedigreeFunction": "numeric",
            "Age": "numeric"
        }
    },
    "adult": {
        "name": "Income Prediction",
        "path": "backend/data/adult.csv",
        "target_column": " class",
        "drop_columns": ["fnlwgt", "education-num", "native-country"],
        "class_labels": {0: "<=50K", 1: ">50K"},
        "feature_types": {
            "age": "numeric",
            "workclass": "categorical",
            "fnlwgt": "numeric",
            "education": "categorical",
            "education-num": "numeric",
            "marital-status": "categorical",
            "occupation": "categorical",
            "relationship": "categorical",
            "race": "categorical",
            "sex": "categorical",
            "capital-gain": "numeric",
            "capital-loss": "numeric",
            "hours-per-week": "numeric",
            "native-country": "categorical"
        }
    },
    "bank": {
        "name": "Credit Approval",
        "path": "backend/data/bank.csv",
        "target_column": "give_credit",
        "class_labels": {0: "Deny Credit", 1: "Approve Credit"},
        "feature_types": {
            "revolving": "numeric",
            "age": "numeric",
            "nbr_30_59_days_past_due_not_worse": "numeric",
            "debt_ratio": "numeric",
            "monthly_income": "numeric",
            "nbr_open_credits_and_loans": "numeric",
            "nbr_90_days_late": "numeric",
            "nbr_real_estate_loans_or_lines": "numeric",
            "nbr_60_89_days_past_due_not_worse": "numeric",
            "dependents": "numeric"
        }
    },
    "compas": {
        "name": "Recidivism Prediction",
        "path": "backend/data/compas.csv",
        "target_column": "is_recid",
        "drop_columns": [
            'id', 'name', 'first', 'last', 
            'compas_screening_date', 'dob', 'c_jail_in', 'c_jail_out',
            'c_case_number', 'c_offense_date', 'c_arrest_date',
            'r_case_number', 'r_charge_degree', 'r_offense_date', 'r_charge_desc',
            'r_jail_in', 'r_jail_out', 'vr_case_number', 'vr_offense_date',
            'vr_charge_desc', 'type_of_assessment', 'decile_score.1',
            'score_text', 'screening_date', 'v_type_of_assessment',
            'v_decile_score', 'v_score_text', 'v_screening_date',
            'in_custody', 'out_custody', 'priors_count.1', 'start', 'end',
            'event', 'decile_score'
        ],
        "class_labels": {0: "No Recidivism", 1: "Recidivism"},
        "feature_types": {
            "id": "numeric",
            "name": "categorical",
            "first": "categorical",
            "last": "categorical",
            "compas_screening_date": "date",
            "sex": "categorical",
            "dob": "date",
            "age": "numeric",
            "age_cat": "categorical",
            "race": "categorical",
            "juv_fel_count": "numeric",
            "decile_score": "numeric",
            "juv_misd_count": "numeric",
            "juv_other_count": "numeric",
            "priors_count": "numeric",
            "days_b_screening_arrest": "numeric",
            "c_jail_in": "datetime",
            "c_jail_out": "datetime",
            "c_case_number": "categorical",
            "c_offense_date": "date",
            "c_arrest_date": "date",
            "c_days_from_compas": "numeric",
            "c_charge_degree": "categorical",
            "c_charge_desc": "categorical",
            "r_case_number": "categorical",
            "r_charge_degree": "categorical",
            "r_days_from_arrest": "numeric",
            "r_offense_date": "date",
            "r_charge_desc": "categorical",
            "r_jail_in": "datetime",
            "r_jail_out": "datetime",
            "violent_recid": "binary",
            "is_violent_recid": "binary",
            "vr_case_number": "categorical",
            "vr_charge_degree": "categorical",
            "vr_offense_date": "date",
            "vr_charge_desc": "categorical",
            "type_of_assessment": "categorical",
            "decile_score.1": "numeric",  # Duplicate column
            "score_text": "categorical",
            "screening_date": "date",
            "v_type_of_assessment": "categorical",
            "v_decile_score": "numeric",
            "v_score_text": "categorical",
            "v_screening_date": "date",
            "in_custody": "date",
            "out_custody": "date",
            "priors_count.1": "numeric",   # Duplicate column
            "start": "date",
            "end": "date",
            "event": "numeric",
            "two_year_recid": "binary"
        }
    },
    "german": {
        "name": "German Credit Risk",
        "path": "backend/data/german_credit.csv",
        "target_column": "default",
        "class_labels": {0: "Good Credit", 1: "Bad Credit"},
        "feature_types": {
            "account_check_status": "categorical",
            "duration_in_month": "numeric",
            "credit_history": "categorical",
            "purpose": "categorical",
            "credit_amount": "numeric",
            "savings": "categorical",
            "present_emp_since": "categorical",
            "installment_as_income_perc": "numeric",
            "personal_status_sex": "categorical",
            "other_debtors": "categorical",
            "present_res_since": "numeric",
            "property": "categorical",
            "age": "numeric",
            "other_installment_plans": "categorical",
            "housing": "categorical",
            "credits_this_bank": "numeric",
            "job": "categorical",
            "people_under_maintenance": "numeric",
            "telephone": "categorical",
            "foreign_worker": "categorical"
        }
    }
}

ML_MODELS = {
    "mlp": "Multi-layer Perceptron",
    "random_forest": "Random Forest",
    "logistic_regression": "Logistic Regression",
    "xgboost": "XGBoost",
    "decision_tree": "Decision Tree",
}

CF_METHODS = {
    "dice": "DiCE (Diverse Counterfactual Explanations)",
    "wachter": "Wachter's Method",
    "cem": "CEM (Contrastive Explanation Method)",
    "face": "FACE (Feasible and Actionable Counterfactual Explanations)",
    "FOCUS": "FOCUS (Feature-wise Counterfactual Explanations)",
    "CCHVAE": "CCHVAE (Counterfactual Explanations with Variational Autoencoders)",
    "foiltrees": "Foil Trees",
}